- name: Install and Run Nginx
  hosts: mongodb
  become: yes
  tasks:
  - name: Install Nginx
    ansible.builtin.yum:
      name: nginx
      state: installed
  - name: Run Nginx
    ansible.builtin.service:
      name: nginx
      state: started      