- name: Entering values from prompt
  hosts: localhost
  vars_prompt:
  - name: NAME
      prompt: Enter User Name
      private: false
  - name: PASSWORD
      prompt: Enter Password
      private: true
  tasks:
   - name: Printing variables entered form prompt
     ansible.builtin.debug:
      msg: "UserName:{{NAME}}, Password:{{PASSWORD}}"