- name: Data Types in Ansible
  hosts: localhost
  vars:
  - age: 30
  - name: "Alekhya"
  - isbolean: TRUE
  - Skills:
      - java
      - devops
      - AWS
  - Experiene:
      - java: 10
      - Devops: 3
      - AWS: 3

  tasks:
  - name: Printing Datatypes
    ansible.builtin.debug:
      msg: "my name is {{name}}, age is {{age}}, information is {{isbolean}} having skills {{Skills[1]}} with experience {{Experiene[java]}}"
   