- name: checking and creating directory if not exists
  hosts: localhost
  vars:
    dir: "/ansible"
  tasks:
   - name: Check Directory
     ansible.builtin.stat:
     register: exitstatus
     ignore_errors: yes

   - name: print exitstatus
     ansible.builtin.debug:
      msg: "output is {{exitstatus}}"

   - name: Create Directory
     ansible.builtin.file:
       path: \home\centos\tmp
       state: directory