- name: Installing 
  hosts: mongodb
  become: yes
  tasks:
    - name: Installing 
      ansible.builtin.yum:
        name: "{{item}}"
        state: installed
      loop:
        - nginx
        - mailx
        - postfix
        - cyrus-sasl-plain

