- name: Installing
  hosts: mongodb
  become: yes
  tasks: 
    - name: Installing 
      ansible.builtin.yum:
        name: "{{item.name}}"
        state: "{{item.state}}"
      loop:
        - {name: 'nginx', state: 'present'}
        - {name: 'postfix', state: 'installed'}
        - {name: 'mailx', state: 'absent'}
        - {name: 'cyrus-sasl-plain', state: 'remove'}
