- name: Installing/removing nginx, postfix, mailx,cyrus-sasl-plain
  hosts: mongodb
  become: yes
  tasks: 
    - name: Installing niginx, postfix. Removing mailx, cyrus-sasl-plain
      ansible.buitin.yum:
        name: "{{item.name}}"
        state: "{{item.state}}"
      loop:
        - {name: 'nginx', state: 'present'}
        - {name: 'postfix', state: 'installed'}
        - {name: 'mailx', state: 'absent'}
        - {name: 'cyrus-sasl-plain', state: 'remove'}
